language: python
cache: pip
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
matrix:
  allow_failures:
    - python: "3.2"  # because of GitPython
install: "pip install -r requirements.txt"
script: python tests.py
